RESULT_APP = shapes
TEST_APP = test

COMPILER_OPTIONS = -c -std=c++17 -I../Source -I./googletest/googletest/include -I./googletest/googletest

# --- Google Test ---
GTEST_SRC = ./googletest/googletest/src/gtest-all.cc
GTEST_MAIN = ./googletest/googletest/src/gtest_main.cc

# TEST_SRC = test.cpp ../Source/Matrix.cpp
TEST_SRC = test.cpp ../Source/App.cpp
TEST_OBJ = $(TEST_SRC:.cpp=.o) $(GTEST_SRC:.cc=.o) $(GTEST_MAIN:.cc=.o)

# --- test app ---
Test: $(TEST_APP)

$(TEST_APP): googletest $(TEST_OBJ)
	g++ $(TEST_OBJ) -o $@

googletest:
	git clone https://github.com/google/googletest.git

.cpp.o:
	g++ $(COMPILER_OPTIONS) $< -o $@

.cc.o:
	g++ $(COMPILER_OPTIONS) $< -o $@

clean:
	rm -f $(TEST_OBJ)
	rm -f *.o $(TEST_APP)

debug:
	echo $(TEST_APP)
	echo $(COMPILER_OPTIONS)
	echo $(TEST_SRC)
	echo $(TEST_OBJ)
